use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'http://10.152.160.21:8080/gtwork_ios/gtmodulesspec.git'

platform :ios, '9.0'

target 'GTResourceModules_Example' do
  pod 'GTResourceModules', :path => '../'

  target 'GTResourceModules_Tests' do
    inherit! :search_paths

    
  end
end
